import { FeatureManifest, FeatureId } from '../types';

export const ONEVA_FEATURE_REGISTRY: Record<FeatureId, FeatureManifest> = {
  oneva_ui: {
    id: 'oneva_ui',
    name: 'ONEVA UI',
    tagline: 'Adaptive luxury system framework',
    description: 'Core aesthetic rendering layer, micro-interactions, responsive typography, and tactile feedback interfaces.',
    version: '1.0.0',
    status: 'verified',
    isLocalOnly: true,
    category: 'core',
    icon: 'Sparkles',
    minClientVersion: '1.0.0',
    supportedAndroidVersions: ['12', '13', '14', '15'],
    remoteConfigKey: 'features.oneva_ui.enabled',
  },
  oneva_glow: {
    id: 'oneva_glow',
    name: 'ONEVA Glow',
    tagline: 'Ambient edge lighting & particle physics engine',
    description: 'Hardware-accelerated edge illumination engine for incoming notifications, calls, and dynamic system state pulses.',
    version: '0.9.4',
    status: 'verified',
    isLocalOnly: true,
    category: 'appearance',
    icon: 'Zap',
    minClientVersion: '1.0.0',
    supportedAndroidVersions: ['13', '14', '15'],
    remoteConfigKey: 'features.oneva_glow.status',
  },
  oneva_themes: {
    id: 'oneva_themes',
    name: 'ONEVA Themes',
    tagline: 'Deep dark neutral & luminance palette system',
    description: 'System-wide theme color matching, high-contrast OLED black calibrations, and customizable palette presets.',
    version: '0.9.1',
    status: 'verified',
    isLocalOnly: true,
    category: 'appearance',
    icon: 'Palette',
    minClientVersion: '1.0.0',
    supportedAndroidVersions: ['12', '13', '14', '15'],
    remoteConfigKey: 'features.oneva_themes.status',
  },
  oneva_icons: {
    id: 'oneva_icons',
    name: 'ONEVA Icons',
    tagline: 'Minimalist vector icon pack architecture',
    description: 'Scalable vector icon engine with custom glyph overrides, masking, and dynamic asset pack loading.',
    version: '0.8.8',
    status: 'verified',
    isLocalOnly: true,
    category: 'appearance',
    icon: 'Shapes',
    minClientVersion: '1.0.0',
    supportedAndroidVersions: ['12', '13', '14', '15'],
    remoteConfigKey: 'features.oneva_icons.status',
  },
  oneva_keyboard: {
    id: 'oneva_keyboard',
    name: 'ONEVA Keyboard',
    tagline: 'Privacy-first tactile IME with localized prediction',
    description: 'Zero-cloud keystroke processing, on-device gesture typing, and custom aesthetic theme support.',
    version: '0.5.0',
    status: 'testing',
    isLocalOnly: true,
    category: 'input',
    icon: 'Keyboard',
    minClientVersion: '1.1.0',
    supportedAndroidVersions: ['13', '14', '15'],
    remoteConfigKey: 'features.oneva_keyboard.status',
  },
  oneva_assist: {
    id: 'oneva_assist',
    name: 'ONEVA Assist',
    tagline: 'On-device contextual intelligence engine',
    description: 'Private, localized smart assistant for quick system controls and routines without cloud audio/command transmission.',
    version: '0.2.0',
    status: 'draft',
    isLocalOnly: true,
    category: 'intelligence',
    icon: 'Cpu',
    minClientVersion: '1.2.0',
    supportedAndroidVersions: ['14', '15'],
    remoteConfigKey: 'features.oneva_assist.status',
  },
  oneva_vision: {
    id: 'oneva_vision',
    name: 'ONEVA Vision',
    tagline: 'Hardware camera neural pipeline',
    description: 'Localized scene recognition and visual processing executed purely on neural processing units (NPU).',
    version: '0.1.0',
    status: 'draft',
    isLocalOnly: true,
    category: 'intelligence',
    icon: 'Eye',
    minClientVersion: '1.2.0',
    supportedAndroidVersions: ['14', '15'],
    remoteConfigKey: 'features.oneva_vision.status',
  },
  oneva_upgrade_center: {
    id: 'oneva_upgrade_center',
    name: 'ONEVA Upgrade Center',
    tagline: 'Differential OTA & asset release distributor',
    description: 'Secure remote version verification, differential updates check, and cryptographically signed asset delivery.',
    version: '1.0.0',
    status: 'verified',
    isLocalOnly: false,
    category: 'system',
    icon: 'ArrowUpCircle',
    minClientVersion: '1.0.0',
    supportedAndroidVersions: ['12', '13', '14', '15'],
    remoteConfigKey: 'features.oneva_upgrade_center.status',
  },
};

export function getAllFeatures(): FeatureManifest[] {
  return Object.values(ONEVA_FEATURE_REGISTRY);
}

export function getFeatureManifest(id: FeatureId): FeatureManifest | undefined {
  return ONEVA_FEATURE_REGISTRY[id];
}
